language: ruby

rvm:
  - 2.0.0-p481
  
addons:
  postgresql: '9.3'

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake spec

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml